spring:
  datasource:
    url: jdbc:mysql://localhost/utb
    username: username
    password: passowrd
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    contexts: production
  mail:
    host: poczta.pl
    port: 25
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000